Repository Jiyun-Parkk/woorifisa-fe-tech-seminar, pull requests merged in 2023-05, with the labels that each got.

#1 [docs] README.md " FE 기술 세미나 주제 정리 "
  README.md
Labels: docs

#15 feat: 반응형 모바일 네비게이션 구현
  src/App.vue
  src/components/Button/MobileNavButton.vue
  src/components/Header.vue
  src/components/Navigation.vue
  src/stores/isMobileNav.js
  src/stores/windowSize.js
Labels: feat

#18 [Docs] README.md " gif 미리보기 추가 "
  README.md
Labels: docs

#19 [Docs] README.md " 로고 및 이미지, 기술 스택 추가 "
  README.md
  src/assets/images/logo-black-bg.png
  src/assets/images/logo-color-bg.png
  src/assets/images/logo-color.png
  src/assets/images/logo-white.png
  src/assets/screenshot.png
Labels: docs

#29 fix: 폰트 다시 적용
  dist/assets/index-12a8ba73.css
  dist/assets/index-6010ecea.js
  dist/assets/index-672e453d.css
  dist/index.html
  src/assets/index.css
Labels: bug
